# -*- coding: latin-1 -*-
"""A worked line of real Clarion for every public member of every class.

The build FAILS if a member has none, so the manual cannot fall behind the
code: add a method and the build tells you the manual is missing an example.
Keys are "Class.Member".  `Mailer` is the global EmailToClass object the
emailTo template declares.
"""

EXAMPLES = {

# =====================================================================
#  EmailNetClass  -  the transport primitives
# =====================================================================
'EmailNetClass.Conn':          "IF Mailer.Net.Conn THEN Mailer.Net.Close().        ! non-zero while a socket is open",
'EmailNetClass.Secure':        "IF NOT Mailer.Net.Secure THEN MESSAGE('This connection is NOT encrypted').",
'EmailNetClass.LastError':     "IF Mailer.Net.LastError = ETNet:Timeout THEN Mailer.Net.Timeout = 60000.",
'EmailNetClass.LastWinError':  "MESSAGE('TLS refused, Windows code ' & Mailer.Net.LastWinError)   ! 590624 = client cert asked for",
'EmailNetClass.LastErrorText': "MESSAGE(CLIP(Mailer.Net.LastErrorText))            ! 'The TLS handshake failed'",
'EmailNetClass.Timeout':       "Mailer.Net.Timeout = 60000                         ! milliseconds; 30000 by default",
'EmailNetClass.VerifyCert':    "Mailer.Net.VerifyCert = 0                          ! ONLY for a self-signed server on your own LAN",
'EmailNetClass.Trace':         "Mailer.Net.Trace = 1                               ! record the conversation in TraceQ",
'EmailNetClass.HidePasswords': "Mailer.Net.HidePasswords = 0                       ! show credentials in the log - never on a customer machine",
'EmailNetClass.Response':      "IF Mailer.Net.RespLen THEN Loc:Body = Mailer.Net.Response[1 : Mailer.Net.RespLen].",
'EmailNetClass.RespLen':       "MESSAGE('The service answered with ' & Mailer.Net.RespLen & ' bytes')",
'EmailNetClass.RespCap':       "MESSAGE('The response buffer currently holds ' & Mailer.Net.RespCap & ' bytes')",
'EmailNetClass.Status':        "IF Mailer.Net.Status = 401 THEN MESSAGE('The API key was rejected').",
'EmailNetClass.BinLen':        "Loc:Sealed = Mailer.Net.Protect('secret'); Loc:Len = Mailer.Net.BinLen",
'EmailNetClass.TraceQ':        "LOOP i = 1 TO RECORDS(Mailer.Net.TraceQ); GET(Mailer.Net.TraceQ, i); Loc:Line = Mailer.Net.TraceQ.Line; END",

'EmailNetClass.Construct':     "Net  EmailNetClass                                 ! Construct runs here, before your CODE",
'EmailNetClass.Destruct':      "!  runs at program end: closes the socket and frees the credential handles",
'EmailNetClass.Open':          "IF NOT Mailer.Net.Open('smtp.gmail.com', 465, 1) THEN MESSAGE(Mailer.Net.LastErrorText).",
'EmailNetClass.StartTls':      "IF NOT Mailer.Net.StartTls('smtp.gmail.com') THEN MESSAGE('TLS upgrade refused').",
'EmailNetClass.Send':          "Mailer.Net.Send('MAIL FROM:<sales@acme.com><13,10>')",
'EmailNetClass.SendLine':      "Mailer.Net.SendLine('AUTH LOGIN ' & Loc:Blob, 1)   ! 1 = a credential, masked in the log",
'EmailNetClass.RecvLine':      "Loc:Reply = Mailer.Net.RecvLine()                  ! '250 2.1.0 Ok', without the CRLF",
'EmailNetClass.Close':         "Mailer.Net.Close()                                 ! polite TLS shutdown, then the socket",
'EmailNetClass.IsOpen':        "IF Mailer.Net.IsOpen() THEN Mailer.Net.SendLine('QUIT').",
'EmailNetClass.Http':          "Loc:Status = Mailer.Net.Http('POST', 'https://api.resend.com/emails', Loc:Hdrs, Loc:Json)",
'EmailNetClass.Body':          "Loc:Reason = Mailer.OAuth.JsonValue(Mailer.Net.Body(), 'message')",
'EmailNetClass.OAuthListen':   "Loc:Id = Mailer.Net.OAuthListen(0, Loc:Port)       ! 0 = let Windows pick a free port",
'EmailNetClass.OAuthWait':     "Loc:Query = Mailer.Net.OAuthWait(Loc:Id, 180, Loc:Html)   ! 'code=4/0Ab...&state=xyz'",
'EmailNetClass.OAuthStop':     "Mailer.Net.OAuthStop(Loc:Id)                       ! always, even after a timeout",
'EmailNetClass.OpenUrl':       "Mailer.Net.OpenUrl('https://accounts.google.com/o/oauth2/v2/auth?...')",
'EmailNetClass.Sha256':        "Loc:Digest = Mailer.Net.Sha256(Loc:Verifier)       ! 32 raw bytes; BinLen is 32",
'EmailNetClass.RandomBytes':   "Loc:Verifier = Mailer.Msg.Base64Url(Mailer.Net.RandomBytes(32))",
'EmailNetClass.Protect':       "Loc:Sealed = Mailer.Net.Protect('my-app-password') ! DPAPI, this Windows user only",
'EmailNetClass.Unprotect':     "Loc:Clear = Mailer.Net.Unprotect(Loc:Sealed[1 : Loc:SealedLen])",
'EmailNetClass.SetErr':        "Mailer.Net.SetErr(ETNet:Timeout)                   ! from a derived class of your own",
'EmailNetClass.AddTrace':      "Mailer.Net.AddTrace('--- retrying with the backup server')",
'EmailNetClass.ClearTrace':    "Mailer.Net.ClearTrace()                            ! before a send, so the log is just this one",
'EmailNetClass.TraceText':     "Loc:Log = Mailer.Net.TraceText()                   ! the whole transcript, CRLF separated",

# =====================================================================
#  EmailBufClass  -  the growing byte buffer
# =====================================================================
'EmailBufClass.Buf':           "Loc:First = Mailer.Msg.Mime.Buf[1 : 100]           ! never read past .Len",
'EmailBufClass.Len':           "MESSAGE('The message is ' & Mailer.Msg.Mime.Len & ' bytes')",
'EmailBufClass.Cap':           "MESSAGE('Capacity ' & Mailer.Msg.Mime.Cap & ', used ' & Mailer.Msg.Mime.Len)",

'EmailBufClass.Construct':     "Buf  EmailBufClass                                 ! starts at 1 KB and doubles",
'EmailBufClass.Destruct':      "!  runs at scope end and releases the buffer",
'EmailBufClass.Need':          "Mailer.Msg.Mime.Need(2000000)                      ! pre-size before a known-big append",
'EmailBufClass.Add':           "Mailer.Msg.TextBody.Add('One more line.')",
'EmailBufClass.AddLen':        "Mailer.Msg.TextBody.AddLen(Loc:Raw, Loc:RawLen)    ! binary-safe: takes the length",
'EmailBufClass.AddLine':       "Mailer.Msg.TextBody.AddLine('Regards,')            ! appends CRLF for you",
'EmailBufClass.ClearAll':      "Mailer.Msg.TextBody.ClearAll()                     ! NOT Clear - that name breaks CLEAR()",
'EmailBufClass.Value':         "Loc:Body = Mailer.Msg.TextBody.Value()",

# =====================================================================
#  EmailMsgClass  -  the message and its MIME
# =====================================================================
'EmailMsgClass.FromAddr':      "Mailer.Msg.FromAddr = 'sales@acme.com'             ! or let the account fill it in",
'EmailMsgClass.FromName':      "Mailer.Msg.FromName = 'Acme Sales'",
'EmailMsgClass.ReplyTo':       "Mailer.Msg.ReplyTo = 'support@acme.com'",
'EmailMsgClass.Subject':       "Mailer.Msg.Subject = 'Factura N<250>mero 42'                ! accents are handled for you",
'EmailMsgClass.Priority':      "Mailer.Msg.Priority = ETPri:High                   ! X-Priority: 1 + Importance: High",
'EmailMsgClass.CharSet':       "Mailer.Msg.CharSet = ETChs:Ansi                    ! send the raw bytes as windows-1252",
'EmailMsgClass.ReadReceipt':   "Mailer.Msg.ReadReceipt = 1                         ! adds Disposition-Notification-To",
'EmailMsgClass.MessageId':     "Mailer.Msg.MessageId = '<' & Loc:Guid & '@acme.com>'   ! blank = generated for you",
'EmailMsgClass.TzMinutes':     "Mailer.Msg.TzMinutes = -300                        ! force the Date: offset; 0 = ask Windows",
'EmailMsgClass.AddrQ':         "LOOP i = 1 TO RECORDS(Mailer.Msg.AddrQ); GET(Mailer.Msg.AddrQ, i); Loc:To = Mailer.Msg.AddrQ.Address; END",
'EmailMsgClass.AttachQ':       "MESSAGE(RECORDS(Mailer.Msg.AttachQ) & ' file(s) attached')",
'EmailMsgClass.HeaderQ':       "MESSAGE(RECORDS(Mailer.Msg.HeaderQ) & ' extra header(s)')",
'EmailMsgClass.TextBody':      "Mailer.Msg.TextBody.Add('Appended after SetText.')",
'EmailMsgClass.HtmlBody':      "IF Mailer.Msg.HtmlBody.Len THEN Loc:IsHtml = 1.",
'EmailMsgClass.Mime':          "Loc:Size = Mailer.Msg.Mime.Len                     ! valid once Build() has run",
'EmailMsgClass.LastError':     "IF Mailer.Msg.LastError = ETMsg:AttachMissing THEN MESSAGE('That file is gone').",
'EmailMsgClass.LastErrorText': "MESSAGE(CLIP(Mailer.Msg.LastErrorText))",
'EmailMsgClass.MaxSize':       "Mailer.Msg.MaxSize = 20000000                      ! refuse to build past 20 MB",

'EmailMsgClass.Construct':     "Msg  EmailMsgClass                                 ! Construct allocates the buffers",
'EmailMsgClass.Destruct':      "!  runs at scope end: frees every buffer and every in-memory attachment",
'EmailMsgClass.ClearAll':      "Mailer.Msg.ClearAll()                              ! start a fresh message",
'EmailMsgClass.SetFrom':       "Mailer.Msg.SetFrom('sales@acme.com', 'Acme Sales')",
'EmailMsgClass.SetSubject':    "Mailer.Msg.SetSubject('Your invoice')",
'EmailMsgClass.AddTo':         "Mailer.Msg.AddTo('bob@example.com', 'Bob Smith')",
'EmailMsgClass.AddCc':         "Mailer.Msg.AddCc('accounts@acme.com')",
'EmailMsgClass.AddBcc':        "Mailer.Msg.AddBcc('archive@acme.com')              ! goes in RCPT TO, never in a header",
'EmailMsgClass.AddList':       "Mailer.Msg.AddList('a@x.com; b@y.com, c@z.com', ETAddr:To)",
'EmailMsgClass.SetText':       "Mailer.Msg.SetText('The invoice is attached.')",
'EmailMsgClass.AddText':       "Mailer.Msg.AddText('<13,10>Thank you for your order.')",
'EmailMsgClass.SetHtml':       "Mailer.Msg.SetHtml('<p>The invoice is <b>attached</b>.</p>')",
'EmailMsgClass.AddHtml':       "Mailer.Msg.AddHtml('<p>Reply to this message with any question.</p>')",
'EmailMsgClass.Attach':        "IF NOT Mailer.Msg.Attach('C:\\inv\\INV-1042.pdf') THEN MESSAGE(Mailer.Msg.LastErrorText).",
'EmailMsgClass.AttachData':    "Mailer.Msg.AttachData('report.csv', Loc:Csv, 'text/csv')",
'EmailMsgClass.AttachInline':  "Mailer.Msg.AttachInline('logo.png', 'logo')        ! then <img src=\"cid:logo\"> in the HTML",
'EmailMsgClass.AddHeader':     "Mailer.Msg.AddHeader('X-Order-Id', Ord:Number)",
'EmailMsgClass.Validate':      "IF NOT Mailer.Msg.Validate() THEN MESSAGE(Mailer.Msg.LastErrorText).",
'EmailMsgClass.Build':         "IF Mailer.Msg.Build() < 0 THEN MESSAGE(Mailer.Msg.LastErrorText).",
'EmailMsgClass.RecipientList': "Loc:Shown = Mailer.Msg.RecipientList(ETAddr:To)    ! 'Bob Smith <bob@example.com>'",
'EmailMsgClass.EnvelopeCount': "LOOP i = 1 TO Mailer.Msg.EnvelopeCount(); Loc:One = Mailer.Msg.EnvelopeAddr(i); END",
'EmailMsgClass.EnvelopeAddr':  "Loc:Rcpt = Mailer.Msg.EnvelopeAddr(1)              ! To, Cc and Bcc, in order",
'EmailMsgClass.Base64':        "Loc:B64 = Mailer.Msg.Base64('Man')                 ! 'TWFu'",
'EmailMsgClass.Base64Len':     "Mailer.Msg.Base64Len(Loc:Raw, Loc:RawLen, Mailer.Msg.Mime)   ! 76-column lines",
'EmailMsgClass.Base64Decode':  "Loc:Raw = Mailer.Msg.Base64Decode('TWFu')          ! 'Man'",
'EmailMsgClass.Base64Url':     "Loc:Chal = Mailer.Msg.Base64Url(Loc:Digest)        ! -_ and no padding, for PKCE",
'EmailMsgClass.QuotedPrintable': "Loc:Qp = Mailer.Msg.QuotedPrintable(Loc:Utf8)    ! 'caf=C3=A9'",
'EmailMsgClass.Utf8':          "Loc:Utf8 = Mailer.Msg.Utf8('Direcci<243>n')                ! Windows-1252 in, UTF-8 out",
'EmailMsgClass.EncodeHeader':  "Loc:Hdr = Mailer.Msg.EncodeHeader('Factura N<250>mero')     ! '=?UTF-8?B?...?='",
'EmailMsgClass.NeedsEncoding': "IF Mailer.Msg.NeedsEncoding(Cus:Name) THEN Loc:Name = Mailer.Msg.EncodeHeader(Cus:Name).",
'EmailMsgClass.BodyNeedsQp':   "IF Mailer.Msg.BodyNeedsQp(Mailer.Msg.TextBody) THEN Loc:Enc = 'quoted-printable'.",
'EmailMsgClass.Boundary':      "Loc:Bound = Mailer.Msg.Boundary()                  ! '----=_emailTo_294294197354795'",
'EmailMsgClass.DateHeader':    "Loc:Date = Mailer.Msg.DateHeader()                 ! 'Sat, 22 Aug 2026 14:04:33 -0600'",
'EmailMsgClass.GuessType':     "Loc:Type = Mailer.Msg.GuessType('invoice.pdf')     ! 'application/pdf'",
'EmailMsgClass.JsonString':    "Loc:Json = '{\"subject\":' & Mailer.Msg.JsonString(Ord:Subject) & '}'",
'EmailMsgClass.SetErr':        "Mailer.Msg.SetErr(ETMsg:TooBig, 'That attachment is over our limit.')",
'EmailMsgClass.LoadFile':      "IF Mailer.Msg.LoadFile('C:\\inv\\INV-1042.pdf', Loc:Buf) THEN Loc:Size = Loc:Buf.Len.",

# =====================================================================
#  EmailOAuthClass  -  the sign-in
# =====================================================================
'EmailOAuthClass.Net':           "Mailer.OAuth.Net.Timeout = 60000                 ! borrowed from EmailToClass, not owned",
'EmailOAuthClass.Msg':           "Loc:B64 = Mailer.OAuth.Msg.Base64Url(Loc:Raw)    ! the borrowed encoder object",
'EmailOAuthClass.LastError':     "IF Mailer.OAuth.LastError = ETSend:Consent THEN MESSAGE('Sign-in was cancelled').",
'EmailOAuthClass.LastErrorText': "MESSAGE(CLIP(Mailer.OAuth.LastErrorText))",
'EmailOAuthClass.AuthUrl':       "MESSAGE('Consent screen: ' & CLIP(Mailer.OAuth.AuthUrl))",
'EmailOAuthClass.TokenUrl':      "MESSAGE('Token endpoint: ' & CLIP(Mailer.OAuth.TokenUrl))",
'EmailOAuthClass.RedirectPort':  "Mailer.OAuth.RedirectPort = 8721                 ! pin it when a firewall rule needs one port",
'EmailOAuthClass.WaitSeconds':   "Mailer.OAuth.WaitSeconds = 300                   ! five minutes to finish signing in",

'EmailOAuthClass.Init':          "Mailer.OAuth.Init(Mailer.Net, Mailer.Msg)        ! EmailToClass.Construct already did this",
'EmailOAuthClass.SetEndpoints':  "Mailer.OAuth.SetEndpoints(Mailer.Acc)            ! fills AuthUrl and TokenUrl from the provider",
'EmailOAuthClass.Authorize':     "IF NOT Mailer.OAuth.Authorize(Mailer.Acc) THEN MESSAGE(Mailer.OAuth.LastErrorText).",
'EmailOAuthClass.Refresh':       "IF NOT Mailer.OAuth.Refresh(Mailer.Acc) THEN Mailer.OAuth.Authorize(Mailer.Acc).",
'EmailOAuthClass.EnsureToken':   "IF NOT Mailer.OAuth.EnsureToken(Mailer.Acc) THEN RETURN.   ! refreshes only if it must",
'EmailOAuthClass.DefaultScope':  "MESSAGE('Asking for: ' & Mailer.OAuth.DefaultScope(Mailer.Acc))",
'EmailOAuthClass.XOAuth2Blob':   "Loc:Blob = Mailer.OAuth.XOAuth2Blob(Mailer.Acc.UserName, Mailer.Acc.AccessToken)",
'EmailOAuthClass.JsonValue':     "Loc:Tok = Mailer.OAuth.JsonValue(Mailer.Net.Body(), 'access_token')",
'EmailOAuthClass.UrlEncode':     "Loc:Enc = Mailer.OAuth.UrlEncode('a b+c')        ! 'a%20b%2Bc'",
'EmailOAuthClass.UrlDecode':     "Loc:Raw = Mailer.OAuth.UrlDecode('a%20b')        ! 'a b'",
'EmailOAuthClass.QueryValue':    "Loc:Code = Mailer.OAuth.QueryValue(Loc:Query, 'code')",
'EmailOAuthClass.SetErr':        "Mailer.OAuth.SetErr(ETSend:Token, 'The tenant refused this application.')",

# =====================================================================
#  EmailToClass  -  the sender
# =====================================================================
'EmailToClass.Acc':             "Mailer.Acc.Host = 'smtp.office365.com'            ! the whole account lives here",
'EmailToClass.Net':             "Mailer.Net.Trace = 1                              ! the transport it owns",
'EmailToClass.OAuth':           "Mailer.OAuth.WaitSeconds = 300",
'EmailToClass.Msg':             "Mailer.Msg.AddTo('bob@example.com')               ! the message SendSimple and Compose use",
'EmailToClass.Language':        "Mailer.Language = ETLng:Spanish                   ! every window and message switches",
'EmailToClass.Silent':          "Mailer.Silent = 1                                 ! never pop a message box; check LastErrorText",
'EmailToClass.Trace':           "Mailer.Trace = 1                                  ! keep the conversation for the Log tab",
'EmailToClass.IniFile':         "Mailer.IniFile = PATH() & '\\mail.ini'             ! the default store, when no table is mapped",
'EmailToClass.IniSection':      "Mailer.IniSection = 'Mail'                        ! section prefix inside that INI",
'EmailToClass.LastError':       "IF Mailer.LastError = ETSend:Auth THEN MESSAGE('Check the password').",
'EmailToClass.LastErrorText':   "MESSAGE(CLIP(Mailer.LastErrorText))               ! always says why",
'EmailToClass.LastServerReply': "MESSAGE('The server said: ' & CLIP(Mailer.LastServerReply))",
'EmailToClass.Capabilities':    "IF INSTRING('XOAUTH2', Mailer.Capabilities, 1, 1) THEN Mailer.Acc.AuthMode = ETAuth:XOAuth2.",

'EmailToClass.Construct':       "Mailer  EmailToClass                              ! builds Net, Msg, OAuth and the buffers",
'EmailToClass.Destruct':        "!  runs at program end: closes any socket and frees everything it built",
'EmailToClass.Init':            "Mailer.Init(PATH() & '\\emailTo.ini')",
'EmailToClass.SetProvider':     "Mailer.SetProvider(ETPrv:Gmail)                   ! host, port, security and sign-in in one call",
'EmailToClass.ProviderName':    "MESSAGE('Sending through ' & Mailer.ProviderName(Mailer.Acc.Provider))",
'EmailToClass.LoadAccount':     "Mailer.LoadAccount('billing')                     ! VIRTUAL - the template points it at your table",
'EmailToClass.SaveAccount':     "Mailer.SaveAccount()                              ! VIRTUAL - what the Setup window calls on Save",
'EmailToClass.Seal':            "Set:Password = Mailer.Seal(Loc:Typed)             ! DPAPI + base64, safe for a text column",
'EmailToClass.Unseal':          "Mailer.Acc.Password = Mailer.Unseal(Set:Password)",
'EmailToClass.Send':            "IF NOT Mailer.Send(Mailer.Msg) THEN Mailer.ShowError().",
'EmailToClass.SendSimple':      "IF NOT Mailer.SendSimple('bob@acme.com','Invoice','It is attached.','INV.pdf') THEN Mailer.ShowError().",
'EmailToClass.TestAccount':     "IF Mailer.TestAccount() THEN MESSAGE('The account works').   ! sends nothing to anybody",
'EmailToClass.SendSmtp':        "Mailer.SendSmtp(Mailer.Msg)                       ! VIRTUAL - override to log every send",
'EmailToClass.SendGmailApi':    "Mailer.Acc.Transport = ETTrn:GmailApi; Mailer.Send(Mailer.Msg)",
'EmailToClass.SendGraphApi':    "Mailer.Acc.Transport = ETTrn:GraphApi; Mailer.Send(Mailer.Msg)",
'EmailToClass.SendApiKey':      "Mailer.Acc.Transport = ETTrn:ApiKey; Mailer.Send(Mailer.Msg)",
'EmailToClass.Authorize':       "IF NOT Mailer.Authorize() THEN MESSAGE(Mailer.LastErrorText).   ! opens the browser",
'EmailToClass.Setup':           "IF Mailer.Setup() THEN Mailer.LoadAccount().      ! the account window; 1 = saved",
'EmailToClass.Compose':         "Mailer.Compose(Cus:Email, 'Your statement', '', Loc:PdfName)",
'EmailToClass.ShowError':       "Mailer.ShowError()                                ! respects Silent; does nothing on success",
'EmailToClass.Txt':             "?SendBtn{PROP:Text} = Mailer.Txt(ETTxt:Send)      ! override Txt to add a third language",
'EmailToClass.SetErr':          "Mailer.SetErr(ETSend:NoAccount, 'No mailbox is configured for this branch.')",
'EmailToClass.EhloDomain':      "MESSAGE('We announce ourselves as ' & Mailer.EhloDomain())",
'EmailToClass.Expect':          "IF NOT Mailer.Expect('250,251') THEN MESSAGE(Mailer.LastServerReply).",
'EmailToClass.SmtpCmd':         "IF NOT Mailer.SmtpCmd('NOOP', '250') THEN MESSAGE('The server stopped answering').",
'EmailToClass.DotStuff':        "Mailer.DotStuff(Mailer.Msg)                       ! doubles a leading '.' on every line",
'EmailToClass.JsonRecipients':  "Loc:To = Mailer.JsonRecipients(Mailer.Msg, ETAddr:To, 'sg')   ! [{\"email\":\"bob@x.com\"}]",
}
